site_name: Awesome Giants
site_url: https://g4brielvs.me
site_description: A curated list of awesome Python frameworks, libraries and software
site_author: g4brielvs
repo_name: g4brielvs/awesome-giants
repo_url: https://github.com/g4brielvs/awesome-giants
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
      link: https://github.com/g4brielvs
    - type: twitter
      link: https://twitter.com/g4brielvs
    - type: linkedin
      link: https://www.linkedin.com/in/g4brielvs
extra_css:
    - css/extra.css
nav:
  - "...by standing on the shoulders of giants" : "index.md"
google_analytics:
    - UA-66296217-2
    - auto